### ISSUE TITLE
Autostart not working with Windows batch file start command

### ISSUE THREAD

**Issue by Red-Leader117** [MrBran4/SET-Challenge-2019#21]
**Describe the bug**
I've discovered that the simulator will not start automatically after drone connection after being called by `start` in a batch file.

I'm trying to create a batch file that automatically starts the simulator and the drones to ease testing. The dro

**To Reproduce**
* Open the command line on Windows
* Enter `start "" "<path to simulator exe>"` and execute
* Connect 5 drones
* The simulator does not start

**Expected behaviour**
The simulator automatically starts as soon as all the drones connect.

**Environment**
 - OS: Windows 10 1809 64-bit
 - Simulator version: 1.2

**Comment by MrBran4** [comment]
The simulator looks for its config file (including the setting to automatically start) in the current running directory. It might be that when you call it with ‘start’, the simulator is running from the directory of the batch file - not the directory of the simulator executable
Can you try launching it from a batch file in the same folder as the simulator executable? If that works, you might have to change your batch script to cd into the simulator folder before starting it
On Fri, Apr 26, 2019 at 13:08, Red-Leader117 <notifications@github.com> wrote:
Describe the bug
I've discovered that the simulator will not start automatically after drone connection after being called by start in a batch file.

I'm trying to create a batch file that automatically starts the simulator and the drones to ease testing. The dro

To Reproduce

 * Open the command line on Windows
 * Enter start "" "<path to simulator exe>" and execute
 * Connect 5 drones
 * The simulator does not start

Expected behaviour
The simulator automatically starts as soon as all the drones connect.

Environment

 * OS: Windows 10 1809 64-bit
 * Simulator version: 1.2

**Comment by Red-Leader117** [comment]
Ah, that does work. Thank you for the quick answer. We'll cd into it then.
